services:
  app:
    container_name: translator-challenge-back
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
        - "8000:80"
    depends_on:
      - db
  db:
    container_name: translator-challenge-db
    image: mongo
    env_file:
      - .env
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

volumes:
    dbdata:
